// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJrwEHvw1xUChgJp7e8_tDLzTeAJDP_Ac',
    appId: '1:761394542856:android:e4b2c507d2b467334d14bd',
    messagingSenderId: '761394542856',
    projectId: 'task-master-feb84',
    databaseURL: 'https://task-master-feb84-default-rtdb.firebaseio.com',
    storageBucket: 'task-master-feb84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBltQ5ZnC-lhzt8kggEk8W4eFa1yMt5HmQ',
    appId: '1:761394542856:ios:6e014a9d032fc1934d14bd',
    messagingSenderId: '761394542856',
    projectId: 'task-master-feb84',
    databaseURL: 'https://task-master-feb84-default-rtdb.firebaseio.com',
    storageBucket: 'task-master-feb84.appspot.com',
    androidClientId: '761394542856-e3vsklg4u5031jvss5hjacfau9v9ci95.apps.googleusercontent.com',
    iosClientId: '761394542856-nlr4fel09n7aklfdkfpulp7g3h30fujb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterReg',
  );
}
